_wandb:
    value:
        cli_version: 0.25.1
        e:
            ll7nazmdhy60l2cjwwrvkhxefv5a97ow:
                args:
                    - configs/knee/config.json
                codePath: my_CDLNet/train.py
                codePathLocal: train.py
                cpu_count: 80
                cpu_count_logical: 80
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "83818971136"
                        used: "28548468736"
                email: ee2178@nyu.edu
                executable: /home/ee2178/scratch/ee2178/miniconda3/envs/env/bin/python3
                git:
                    commit: fdab4c8305b79c569f7f0f304e264883e43149a9
                    remote: git@github.com:ee2178/Denoising-Diffusion-Project.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c7535cb2-2505-f787-c991-b1f05132f3c0
                host: ga021.hpc.nyu.edu
                memory:
                    total: "1081288454144"
                os: Linux-5.14.0-570.12.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /scratch/ee2178/Denoising-Diffusion-Project/my_CDLNet/train.py
                python: CPython 3.9.25
                root: /scratch/ee2178/Denoising-Diffusion-Project/my_CDLNet
                slurm:
                    array_job_id: "4378346"
                    array_task_count: "5"
                    array_task_id: "0"
                    array_task_max: "4"
                    array_task_min: "0"
                    array_task_step: "1"
                    cluster_name: torch
                    conf: /opt/slurm/data/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: torch_pr_89_tandon_advanced
                    job_cpus_per_node: "16"
                    job_end_time: "1773872883"
                    job_gid: "3711906"
                    job_gpus: "1"
                    job_id: "4380951"
                    job_name: LPDSNet-Knee
                    job_nodelist: ga021
                    job_num_nodes: "1"
                    job_partition: a100_tandon
                    job_qos: gpu48
                    job_start_time: "1773700083"
                    job_uid: "3711906"
                    job_user: ee2178
                    jobid: "4380951"
                    jobtmp: /state/partition1/job-4380951
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: ga021
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /scratch/ee2178/Denoising-Diffusion-Project/my_CDLNet/slurm
                    submit_host: torch-login-1.hpc-infra.svc.cluster.local
                    task_pid: "3870537"
                    tasks_per_node: "1"
                    tmpdir: /state/partition1/job-4380951
                    topology_addr: ga021
                    topology_addr_pattern: node
                    tres_per_task: cpu=16
                startedAt: "2026-03-16T22:28:57.418479Z"
                writerId: ll7nazmdhy60l2cjwwrvkhxefv5a97ow
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 16
            "4": 3.9.25
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
model:
    value:
        C: 1
        K: 30
        M: 169
        P: 7
        adaptive: true
        s: 2
paths:
    value:
        ckpt: null
        save: trained_nets/knee/LPDSNet
train:
    value:
        fit:
            backtrack_thresh: 5
            clip_grad: 0.05
            demosaic: false
            epochs: null
            max_steps: 300000
            mcsure: false
            noise_dist: log
            noise_std:
                - 0
                - 126
            save_every: 5000
            save_freq: 5
            val_every: 2000
            val_freq: 50
            verbose: true
        loaders:
            batch_size: 32
            brain: false
            center_crop: 320
            crop_size: 128
            end_slice: 25
            load_color: false
            num_workers: 14
            scaling_fac: 4000
            start_slice: 10
            trn_path_list:
                - ../../datasets/fastmri_preprocessed/knee_coil_combined/pd/train
            tst_path_list:
                - ../../datasets/fastmri_preprocessed/knee_coil_combined/pd/test
            val_path_list:
                - ../../datasets/fastmri_preprocessed/knee_coil_combined/pd/val
        opt:
            lr: 0.0005
        sched:
            gamma: 0.95
            step_size: 50
type:
    value: LPDSNet
